### PR TITLE
Migrate to codemod-cli

### PR DESCRIPTION
**Pull request by simonihmig**
This removes much of the custom boilerplate (test setup, bin-support) in favor of `codemod-cli`. 🎉

/cc @rwjblue @chriskrycho

The invocation of the CLI is now a bit different, e.g.:
Before: `ember-test-helpers-codemod --type=integration tests/integration`
After: `ember-test-helpers-codemod integration tests/integration`

I could write a little check in `cli.js` to also support the old `--type` param, to remain backwards compatible, or bump the major version (*which I would have to do anyways because of dropping node 4*). Leaning towards the latter...

@kellyselden updating the invocation for `ember-cli-update` would just be a matter of updating the "manifest" (https://github.com/ember-cli/ember-cli-update-codemods-manifest/blob/v2/manifest.json#L19-L20), right? This would automatically get pulled in, users would not have to update their `ember-cli-update` version, right?

### CODE REVIEW

**Comment by rwjblue** [comment]
> This removes much of the custom boilerplate (test setup, bin-support) in favor of codemod-cli. 🎉


Awesome! How was it? Please shoot me any issues with your thoughts on what can be made better/easier...

**Comment by simonihmig** [comment]
> How was it?

@rwjblue pretty straightforward actually! Mainly moving files around, fixing imports etc. Given this was an existing codemod, I just had to figure out how `codemod-cli` expects to have things laid out, for a new codemod I would expect this to be even easier. So nothing to complain, nice job btw! 😆

Just one thing I wondered: if it makes sense to have some test harness for testing that `cli.js` is working. I guess the underlying function from `codemod-cli` (`runTransform`) is probably tested, but as there is some code in `cli.js` itself (*that users might customize, as I was thinking about*) it might be useful to have this tested in the codemod itself as well? There was some `bin-test.js` before (in parts stolen from `ember-modules-codemod` iirc), that test coverage seems to be missing now...

**Comment by kellyselden** [comment]
yep just a manifest update

**Comment by rwjblue** [comment]
Ya, @simonihmig that makes total sense. We should definitely add a cli/bin script test harness.

**Pull request merged**
